#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Set Hostname
  hosts: Ubuntu
  sudo: True
  tasks:
    - name: Set the hostname to clean-slate
      hostname: name=just-a-test
